### ISSUE TITLE
Fix calc-dev deployment - fails on Step 4

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1129]
Fails on `step/4` of price list upload. Not sure what the issue is.

<details>
  <summary>error log from calc-dev</summary>
 
```
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR [16/Dec/2016 17:36:25] ERROR [django.request:256] Internal Server Error: /data-capture/step/4
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR Traceback (most recent call last):
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/newrelic-2.70.0.51/newrelic/hooks/framework_django.py", line 503, in wrapper
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return wrapped(*args, **kwargs)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/data_capture/views/common.py", line 156, in wrapper
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return func(*args, **kwargs)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return view_func(request, *args, **kwargs)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return view_func(request, *args, **kwargs)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/views/decorators/http.py", line 45, in inner
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return func(request, *args, **kwargs)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/data_capture/decorators.py", line 44, in wrapper
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return function(request, *args, **kwargs)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/contextlib.py", line 30, in inner
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return func(*args, **kwds)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/data_capture/views/price_list_upload.py", line 363, in step_4
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     'preferred_schedule_title': pl_details['preferred_schedule'].title,
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/data_capture/views/common.py", line 198, in render
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     self.context(context))
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     template_name, context, request=request, using=using)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader.py", line 99, in render_to_string
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return template.render(context, request)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return self.template.render(context)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 210, in render
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return self._render(context)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return self.nodelist.render(context)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 905, in render
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     bit = self.render_node(node, context)
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
2016-12-16T11:36:25.69-0600 [APP/PROC/WEB/0]ERR     return node.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return compiled_parent._render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return self.nodelist.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 905, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     bit = self.render_node(node, context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return node.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return compiled_parent._render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return self.nodelist.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 905, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     bit = self.render_node(node, context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return node.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return compiled_parent._render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return self.nodelist.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 905, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     bit = self.render_node(node, context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return node.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/newrelic-2.70.0.51/newrelic/hooks/framework_django.py", line 715, in wrapper
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return wrapped(*args, **kwargs)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     result = block.nodelist.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 905, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     bit = self.render_node(node, context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return node.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/newrelic-2.70.0.51/newrelic/hooks/framework_django.py", line 715, in wrapper
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return wrapped(*args, **kwargs)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     result = block.nodelist.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 905, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     bit = self.render_node(node, context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return node.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/defaulttags.py", line 329, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return nodelist.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 905, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     bit = self.render_node(node, context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return node.render(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/templatetags/static.py", line 105, in render
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     url = self.url(context)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 16, in url
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return static(path)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 9, in static
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     return staticfiles_storage.url(path)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 131, in url
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     hashed_name = self.stored_name(clean_name)
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     cache_name = self.clean_name(self.hashed_name(name))
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR     (clean_name, self))
2016-12-16T11:36:25.70-0600 [APP/PROC/WEB/0]ERR ValueError: The file 'frontend/built/js/data-capture-price-list-upload-step-4/index.min.js' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f050339d0b8>.
```
</summary>

**Comment by jseppi** [comment]
So I think what happened is there was a bad merge, which lead the non-existing `'frontend/built/js/data-capture-price-list-upload-step-4/index.min.js'` being included back in `step_4.html`.
I removed it in commit  https://github.com/18F/calc/commit/0611a2ff2b52ba7ed343ef92a7c053f24abf26e5#diff-6c37d2c589fca1c8cfdfd10779a6399dL131 but it looks like it was back in there in the following commit https://github.com/18F/calc/blob/2e3c4202351797e38856b8a423d40dac47a51a89/data_capture/templates/data_capture/price_list/step_4.html#L132

**Comment by jseppi** [comment]
Any way we can test for stuff like this (basically bad static file references) so that Whitenoise doesn't pwn us again?
