### ISSUE TITLE
Dependency Installation

### ISSUE THREAD

**Issue by josefdaly** [18F/calc#1603]
```
Collecting git+git://github.com/18F/djorm-ext-pgfulltext@7ce6606dcb2c4fdd235439b6adcadeb143974a62 (from -r requirements.txt (line 9))
  Cloning git://github.com/18F/djorm-ext-pgfulltext (to 7ce6606dcb2c4fdd235439b6adcadeb143974a62) to /private/var/folders/l8/q7lhvgk94pg8w5981ftsk4hm0000gn/T/pip-wprjtykf-build
  Could not find a tag or branch '7ce6606dcb2c4fdd235439b6adcadeb143974a62', assuming commit.
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pbr/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
    Couldn't find index page for 'pbr' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
    No local packages or working download links found for pbr
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l8/q7lhvgk94pg8w5981ftsk4hm0000gn/T/pip-wprjtykf-build/setup.py", line 8, in <module>
        setup_requires=['pbr'],
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr')
```

Choking on `pbr`.

Solution appeared to be to install pbr. So it should probably be added to the requirements file?

**Comment by toolness** [comment]
Oh weird... I am not familiar with [`pbr`](https://pypi.python.org/pypi/pbr), and as far as I know it's not an implicit dependency of CALC either. Maybe we should figure out what's causing it to try to be imported and remove it, instead of adding it to the requirements?

**Comment by cmc333333** [comment]
[Looks like](https://github.com/18F/djorm-ext-pgfulltext/blob/86e186dad964c37e9485c979e6fc0c7e518cbf33/setup.py#L8) it's a dependency of djorm-ext-pgfulltext, which is [included](https://github.com/18F/calc/blob/eaa1ab227a5a07f5f4f7d2c64a278977cd43cb18/requirements.txt#L9) in the calc's requirements file. Any chance that could be removed in favor of the Postgres functionality now built-in to Django?

**Comment by toolness** [comment]
Yep, we'd wanted to do that, but unfortunately we ran out of budget in early 2017, so we couldn't upgrade to Django 1.10 (the release which introduced native full-text search), let alone migrate off djorm-ext-pgfulltext.  Now that we have funding and just upgraded to 1.10, though, we should be able to do it!

Just created #1645 to address this, and closing this issue in favor of it!
