### ISSUE TITLE
numpy warning

### ISSUE THREAD

**Issue by theresaanna** [18F/calc#250]
Frequently, a warning occurs in the logs that says "Degrees of freedom <= 0 for slice". My suspicion is that its happening when calculating the standard deviation for the rates view in the api app.

```2015-09-14T16:39:32.58+0000 [RTR/0] OUT calc.gsa.gov - [14/09/2015:16:39:31 +0000] "GET /api/rates/?format=json&histogram=12&sort=current_price&query_type=match_all&min_experience=0&max_experience=45&contract-year=current&experience_range=0%2C45 HTTP/1.1" 200 0 71148 "https://calc.gsa.gov/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10" 127.0.0.1:1870 x_forwarded_for:"24.7.115.52, 24.7.115.52, 127.0.0.1, 54.208.160.112" vcap_request_id:c0dc7e59-d9dc-42d1-53bf-8d1267624b1c response_time:0.797094967 app_id:bcfe578b-f721-4e59-bd18-2e496526acf3
2015-09-14T16:39:32.66+0000 [App/1] ERR WARNING:py.warnings:/app/.heroku/python/lib/python3.4/site-packages/numpy/core/_methods.py:83: RuntimeWarning: Degrees of freedom <= 0 for slice
2015-09-14T16:39:32.66+0000 [App/1] ERR warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
2015-09-14T16:39:32.66+0000 [App/1] ERR WARNING:py.warnings:/app/.heroku/python/lib/python3.4/site-packages/numpy/core/_methods.py:95: RuntimeWarning: invalid value encountered in true_divide
2015-09-14T16:39:32.66+0000 [App/1] ERR arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
2015-09-14T16:39:32.66+0000 [App/1] ERR WARNING:py.warnings:/app/.heroku/python/lib/python3.4/site-packages/numpy/core/_methods.py:117: RuntimeWarning: invalid value encountered in double_scalars
2015-09-14T16:39:32.66+0000 [App/1] ERR ret = ret.dtype.type(ret / rcount)```

**Comment by borromeotlhs** [comment]
Is it possible to set warnings to errors for a traceback, as per SO post:http://stackoverflow.com/questions/24513013/traceback-from-a-warning
?

That should give a better picture of what exactly is causing the warning.

**Comment by toolness** [comment]
I'm able to reproduce this bug, as well as a few other warnings, with `python manage.py test api.tests.ContractsTest.test_empty_results`:

```
Creating test database for alias 'default'...
/usr/local/lib/python3.4/site-packages/numpy/core/_methods.py:83: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)

/usr/local/lib/python3.4/site-packages/numpy/core/_methods.py:95: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)

/usr/local/lib/python3.4/site-packages/numpy/core/_methods.py:117: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

.
----------------------------------------------------------------------
Ran 1 test in 0.163s

OK
```

**Comment by toolness** [comment]
One can also use the [`PYTHONWARNINGS`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS) environment variable to turn warnings into exceptions. Setting `PYTHONWARNINGS=error:degrees` yields the following traceback:

```pytb
Traceback (most recent call last):
  File "/calc/api/tests.py", line 63, in test_empty_results
    resp = self.c.get(self.path, {'q': 'nsfr87y3487h3rufbf'})
  File "/usr/local/lib/python3.4/site-packages/django/test/client.py", line 500, in get
    **extra)
  File "/usr/local/lib/python3.4/site-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/usr/local/lib/python3.4/site-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.4/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/calc/api/views.py", line 194, in get
    page_stats['first_standard_deviation'] = np.std(current_rates)
  File "/usr/local/lib/python3.4/site-packages/numpy/core/fromnumeric.py", line 2836, in std
    keepdims=keepdims)
  File "/usr/local/lib/python3.4/site-packages/numpy/core/_methods.py", line 125, in _std
    keepdims=keepdims)
  File "/usr/local/lib/python3.4/site-packages/numpy/core/_methods.py", line 83, in _var
    warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
RuntimeWarning: Degrees of freedom <= 0 for slice
```
