### ISSUE TITLE
Following README.md to setup project fails

### ISSUE THREAD

**Issue by mshenfield** [18F/calc#254]
Following the instructions from the [README](https://github.com/18F/calc/blob/master/README.md) throws an error when you get to the `.\manage.py syncdb` step. The stack trace is as follow:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mshenfield/.pyenv/versions/2.7.8/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/mshenfield/.pyenv/versions/2.7.8/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/Users/mshenfield/.pyenv/versions/2.7.8/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/Users/mshenfield/.pyenv/versions/2.7.8/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/mshenfield/.pyenv/versions/2.7.8/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/mshenfield/.pyenv/versions/2.7.8/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/mshenfield/Source/Workspace/calc/hourglass/settings.py", line 14, in <module>
    import dj_database_url
ImportError: No module named dj_database_url
```

Running `pip install dj_database_url` stops it from throwing this error.
 
===

Included the the commands I ran (at the root of the project tree) and some version information JIC:

__Update local_settings__
`cp hourglass/local_settings.example.py hourglass/local_settings.py`
`vim hourglass/local_settings.py #Update the DATABASE['default']['USER'] and ['PASSWORD'] to 'hourglass'`

__Setup database__
`createdb hourglass`
`createuser hourglass #Enter password hourglass for prompt`

__Setup virtualenv and install dependencies__
`mkvirtualenv 18f-calc`
`pip install -r requirements.txt`

Python Version: 2.7.8
PostgreSQL Version: 9.3.4
Virtualenv Version: 13.1.0

**Comment by mshenfield** [comment]
Ahhh, this is really embarassing, and definitely a personal problem. I switched tabs and didn't run `workon 18f-calc`.
