### ISSUE TITLE
Deployment - error when pushing all three apps in manifest-prod-a

### ISSUE THREAD

**Issue by jseppi** [18F/calc#877]
```sh
 cf push -f manifests/manifest-prod-a.yml
```

works deploying `calc-prod-a` and `calc-rq-worker-a`, but then fails when it gets to `calc-rqworker-a`:

```txt
Starting app calc-rqworker-a in org oasis / space calc-prod as james.seppi@gsa.gov...
panic: send on closed channel

goroutine 893 [running]:
panic(0x6ea700, 0xc820d55100)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:464 +0x3e6
github.com/cloudfoundry/cli/cf/api.(*LoggregatorLogsRepository).flushMessageQueue.func1(0xc821dbc690)
	/Users/cffadmin/concourse-work-dir/containers/00002kcgp1v/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/api/log_repository.go:107 +0x40
github.com/cloudfoundry/cli/cf/api.(*Loggregator_SortedMessageQueue).EnumerateAndClear(0xc8201a2a60, 0xc820310748)
	/Users/cffadmin/concourse-work-dir/containers/00002kcgp1v/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/api/loggregator_message_queue.go:46 +0x103
github.com/cloudfoundry/cli/cf/api.(*LoggregatorLogsRepository).flushMessageQueue(0xc8204f30c0, 0xc821af42a0)
	/Users/cffadmin/concourse-work-dir/containers/00002kcgp1v/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/api/log_repository.go:108 +0x45
github.com/cloudfoundry/cli/cf/api.(*LoggregatorLogsRepository).TailLogsFor.func1(0xc8203d5280, 0xc8204f30c0, 0xc821af42a0)
	/Users/cffadmin/concourse-work-dir/containers/00002kcgp1v/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/api/log_repository.go:89 +0x78
created by github.com/cloudfoundry/cli/cf/api.(*LoggregatorLogsRepository).TailLogsFor
	/Users/cffadmin/concourse-work-dir/containers/00002kcgp1v/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/api/log_repository.go:91 +0x383
```

**Comment by rogeruiz** [comment]
Take a look at this, and make sure you have the latest version of the CLI. 

https://github.com/cloudfoundry/cli/issues/818#issuecomment-216738667

**Comment by jseppi** [comment]
Woot, upgrading my `cf-cli` worked. Thanks!

**Comment by rogeruiz** [comment]
:tada: awesome! I would update the documentation around requiring that version or above so the whole team can be on the same page regarding CLI versions. Also make sure the CI installs that version or above. :+1:

**Comment by jseppi** [comment]
Re-opening so I don't forget ^^
