### ISSUE TITLE
rqscheduler job times out on Region 10 Bulk Upload processing

### ISSUE THREAD

**Issue by jseppi** [18F/calc#888]
I just tried to do a R10 bulk upload on staging, and the web app portion of things went well, but the data were never actually loaded in CALC.

From the `rqworker` logs, it looks like the data processing job is timing out. See below.

<details>
<summary>Logs from calc-dev's rqworker</summary>
```txt
2016-10-06T15:25:20.68-0500 [App/0]      ERR [06/Oct/2016 20:25:20] INFO [rq.worker:478] default: data_capture.jobs.process_bulk_upload_and_send_email(106) (ce0b821b-9d94-4086-b64b-34b602453da3)
2016-10-06T15:25:20.70-0500 [App/0]      ERR [06/Oct/2016 20:25:20] INFO [contracts:62] Starting bulk upload processing (pk=106).
2016-10-06T15:25:20.92-0500 [App/0]      ERR [06/Oct/2016 20:25:20] INFO [contracts:22] Deleting contract objects related to region 10.
2016-10-06T15:25:20.96-0500 [App/0]      ERR [06/Oct/2016 20:25:20] INFO [contracts:33] Generating new contract objects.
2016-10-06T15:26:25.17-0500 [App/0]      ERR [06/Oct/2016 20:26:25] INFO [contracts:42] Saving new contract objects.
2016-10-06T15:28:21.41-0500 [App/0]      ERR [06/Oct/2016 20:28:21] ERROR [contracts:74] An exception occurred during bulk upload processing (pk=106).
2016-10-06T15:28:21.41-0500 [App/0]      ERR Traceback (most recent call last):
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/home/vcap/app/data_capture/jobs.py", line 69, in process_bulk_upload_and_send_email
2016-10-06T15:28:21.41-0500 [App/0]      ERR     num_contracts, num_bad_rows = _process_bulk_upload(upload_source)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/contextlib.py", line 30, in inner
2016-10-06T15:28:21.41-0500 [App/0]      ERR     return func(*args, **kwds)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/home/vcap/app/data_capture/jobs.py", line 45, in _process_bulk_upload
2016-10-06T15:28:21.41-0500 [App/0]      ERR     Contract.objects.bulk_create(contracts)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
2016-10-06T15:28:21.41-0500 [App/0]      ERR     return getattr(self.get_queryset(), name)(*args, **kwargs)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 392, in bulk_create
2016-10-06T15:28:21.41-0500 [App/0]      ERR     self._batched_insert(objs_without_pk, fields, batch_size)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 937, in _batched_insert
2016-10-06T15:28:21.41-0500 [App/0]      ERR     using=self.db)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
2016-10-06T15:28:21.41-0500 [App/0]      ERR     return getattr(self.get_queryset(), name)(*args, **kwargs)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 920, in _insert
2016-10-06T15:28:21.41-0500 [App/0]      ERR     return query.get_compiler(using=using).execute_sql(return_id)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
2016-10-06T15:28:21.41-0500 [App/0]      ERR     cursor.execute(sql, params)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
2016-10-06T15:28:21.41-0500 [App/0]      ERR     return self.cursor.execute(sql, params)
2016-10-06T15:28:21.41-0500 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/rq/timeouts.py", line 51, in handle_death_penalty
2016-10-06T15:28:21.41-0500 [App/0]      ERR     'value ({0} seconds)'.format(self._timeout))
2016-10-06T15:28:21.41-0500 [App/0]      ERR rq.timeouts.JobTimeoutException: Job exceeded maximum timeout value (180 seconds)
```
</details>

**Comment by toolness** [comment]
wut. why is there a max value of 180 seconds on these jobs.

**Comment by jseppi** [comment]
I don't know...

I'm wondering if we should also increase the memory on our workers. Both in prod and staging they are only set to `256M`.

**Comment by jseppi** [comment]
I experimented upping the memory of `calc-rqworker` to `512M` and it worked.
